/*
Generated by Mix
Wed Jul 27 23:26:56 2016 GMT-0400
*/

var Rating = {
	"abi": "[{\"constant\":false,\"inputs\":[{\"name\":\"_key\",\"type\":\"bytes32\"},{\"name\":\"_value\",\"type\":\"uint256\"}],\"name\":\"setRating\",\"outputs\":[],\"type\":\"function\"},{\"constant\":true,\"inputs\":[{\"name\":\"\",\"type\":\"bytes32\"}],\"name\":\"ratings\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"type\":\"function\"}]",
	"codeHex": "0x6060604052605f8060106000396000f3606060405260e060020a600035046350b7b7a2811460245780636c71d01d14603e575b005b600435600090815260208190526040902060243590556022565b605560043560006020819052908152604090205481565b6060908152602090f3",
	"name": "Rating"
}

